name: Generate pac file

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - "master"
    paths:
      - "rules.txt"
      - "config.ini"
  workflow_dispatch:

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Setup generate tool
        uses: BSFishy/pip-action@v1
        with:
          packages: genpac

      - name: Run generate tool
        run: genpac --config-from ./config.ini > pac.txt

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit and push
        uses: EndBug/add-and-commit@v5.3.0
        with:
          message: "chore: ${{ steps.date.outputs.date }} update pac.txt"
          add: "pac.txt"
          author_name: "NoDocCat"
          author_email: "nodoccat@outlook.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
